-- MySQL Script generated by MySQL Workbench
-- Fri Feb  4 14:11:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbtracking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbtracking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbtracking` DEFAULT CHARACTER SET utf8 ;
USE `dbtracking` ;

-- -----------------------------------------------------
-- Table `dbtracking`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtracking`.`User` (
  `id` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtracking`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtracking`.`Product` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtracking`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtracking`.`Location` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `latitude` DOUBLE NULL,
  `longtitude` DOUBLE NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtracking`.`Track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtracking`.`Track` (
  `id` VARCHAR(255) NOT NULL,
  `User_id` VARCHAR(255) NOT NULL,
  `Product_id` VARCHAR(255) NOT NULL,
  `track_qr_code` LONGBLOB NULL,
  `url_track` VARCHAR(255) NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `User_id`, `Product_id`),
  INDEX `fk_Track_User_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Track_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Track_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `dbtracking`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Track_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `dbtracking`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtracking`.`StatusTrack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtracking`.`StatusTrack` (
  `id` VARCHAR(255) NOT NULL,
  `Track_id` VARCHAR(255) NOT NULL,
  `Location_id` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `Track_id`, `Location_id`),
  INDEX `fk_StatusTrack_Track1_idx` (`Track_id` ASC) VISIBLE,
  INDEX `fk_StatusTrack_Location1_idx` (`Location_id` ASC) VISIBLE,
  CONSTRAINT `fk_StatusTrack_Track1`
    FOREIGN KEY (`Track_id`)
    REFERENCES `dbtracking`.`Track` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StatusTrack_Location1`
    FOREIGN KEY (`Location_id`)
    REFERENCES `dbtracking`.`Location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
